### ISSUE TITLE
Please create a comfy node to use it

### ISSUE THREAD

**Issue by wardensc2** [mit-han-lab/nunchaku#14]
Dear mit-han-lab

Thank you so much for your effort to create nunchaku and deepcompressor however it's quite difficult for normal people like us to use.
Can you create a node to load your flux-int4 model in comfyUI

Thank in advance

**Comment by CaiNiaoCYY** [comment]
+1

**Comment by lmxyy** [comment]
Will look into it.

**Comment by lmxyy** [comment]
Hi, comfyui is supported now. Please follow this [doc](https://github.com/mit-han-lab/nunchaku/blob/main/comfyui/README.md) for the usage. Enjoy!

**Comment by zhaoqi571436204** [comment]
> 您好，现在支持 comfyui。请按照此[文档](https://github.com/mit-han-lab/nunchaku/blob/main/comfyui/README.md)进行使用。享受！

Why not make a complete plugin and install it directly from comfyui manage

**Comment by zhaoqi571436204** [comment]
> 您好，现在支持 comfyui。请按照此[文档](https://github.com/mit-han-lab/nunchaku/blob/main/comfyui/README.md)进行使用。享受！

Traceback (most recent call last):                                                                                             
  File "D:\AI\ComfyUI\nodes.py", line 2037, in load_custom_node                                                                
    module_spec.loader.exec_module(module)                                                                                     
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module                                                      
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed                                                 
  File "D:\AI\ComfyUI\custom_nodes\svdquant\__init__.py", line 7, in <module>                                                  
    from .nodes import NODE_CLASS_MAPPINGS                                                                                     
  File "D:\AI\ComfyUI\custom_nodes\svdquant\nodes.py", line 17, in <module>                                                    
    from nunchaku.models.transformer_flux import NunchakuFluxTransformer2dModel                                                
ModuleNotFoundError: No module named 'nunchaku'
