### ISSUE TITLE
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

### ISSUE THREAD

**Issue by ziyanxzy** [mit-han-lab/nunchaku#32]
Processing d:\valencia\nunchaku
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      C:\Users\SAS\AppData\Local\Temp\pip-build-env-7ix_hmr5\overlay\Lib\site-packages\torch\_subclasses\functional_tensor.py:295: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
        cpu = _conversion_method_template(device=torch.device("cpu"))
      Traceback (most recent call last):
        File "C:\Users\SAS\miniforge3\envs\nunchaku\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\SAS\miniforge3\envs\nunchaku\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\SAS\miniforge3\envs\nunchaku\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\SAS\AppData\Local\Temp\pip-build-env-7ix_hmr5\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\SAS\AppData\Local\Temp\pip-build-env-7ix_hmr5\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "C:\Users\SAS\AppData\Local\Temp\pip-build-env-7ix_hmr5\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 83, in <module>
        File "C:\Users\SAS\AppData\Local\Temp\pip-build-env-7ix_hmr5\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 1078, in CUDAExtension
          library_dirs += library_paths(cuda=True)
                          ^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\SAS\AppData\Local\Temp\pip-build-env-7ix_hmr5\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 1216, in library_paths
          paths.append(_join_cuda_home(lib_dir))
                       ^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\SAS\AppData\Local\Temp\pip-build-env-7ix_hmr5\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 2416, in _join_cuda_home
          raise OSError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by fheckeler** [comment]
Same Problem. How to solve ?
