### ISSUE TITLE
When set DEBUG = True in setup.py, I get the following error:

### ISSUE THREAD

**Issue by Lenan22** [mit-han-lab/nunchaku#36]
when run "pip install -e",

Traceback (most recent call last):
  File "SVDQuant/nunchaku/example.py", line 3, in <module>
    from nunchaku.pipelines import flux as nunchaku_flux
  File "SVDQuant/nunchaku/nunchaku/pipelines/flux.py", line 7, in <module>
    from ..models.flux import inject_pipeline, load_quantized_model
  File "nunchaku/nunchaku/models/flux.py", line 11, in <module>
    from .._C import QuantizedFluxModel
ImportError: nunchaku/nunchaku/_C.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN26FluxSingleTransformerBlock7forwardE6TensorS0_S0_

**Comment by Lenan22** [comment]
Do I need to turn on the debug mode if I want the log information of spdlog::debug?

**Comment by xmfbit** [comment]
@Lenan22 To get the output of `spdlog::debug`, I add this method and set the logging level to `debug`:

```
void set_log_level(const std::string& level) {
    auto enum_level = spdlog::level::from_str(level);
    spdlog::set_level(enum_level);
}

// where you want to set logging level
set_log_level("debug");
```

**Comment by Lenan22** [comment]
@xmfbit Could you please tell me in which file you added these codes?

**Comment by pyoliu** [comment]
Have you solved this problem? I'm also troubled

**Comment by lmxyy** [comment]
We have released the Linux wheels for installation. Check [here](https://github.com/mit-han-lab/nunchaku?tab=readme-ov-file#wheels-linux-only-for-now) for the install guide.
