### ISSUE TITLE
Even if it does not download the model, initialization takes 48gb ram.

### ISSUE THREAD

**Issue by vgabbo** [mit-han-lab/nunchaku#40]
As for @lmxyy 's request, I am opening a separate issue. I have a pc with a 4060ti with 16gb vram and 32gb Ram. 
When I start the example.py, it fills the entire 32gb of ram, goes up with 8gb of swap and then it kills the process. I have downloaded the latest codebase.

I have tried with cpu offload, but it still gives problems. Can you please give me an advise?

Here is the modified example I use: 

import torch

from nunchaku.pipelines import flux as nunchaku_flux

pipeline = nunchaku_flux.from_pretrained(
"black-forest-labs/FLUX.1-schnell",
torch_dtype=torch.bfloat16,
qmodel_path="mit-han-lab/svdq-int4-flux.1-schnell",
#qmodel_path="mit-han-lab/svdquant-models/svdq-int4-flux.1-schnell.safetensors", # download from Huggingface
).to("cuda")

pipeline.enable_sequential_cpu_offload()

image = pipeline("A cat holding a sign that says hello world", num_inference_steps=4, guidance_scale=0).images[0]
image.save("example.png")

Thank you for your patience and your amazing work.

**Comment by greenyellowmill** [comment]
Same problem i had, reverted to previous commit and it worked normally without ballooning memory

**Comment by lmxyy** [comment]
I've fixed it. Could you pull the latest code and try again?

**Comment by vgabbo** [comment]
Hi! Thank you very much for your work. Sadly, I tried to download and reinstall it, it currently acts differently: it does not kill it anymore in the same way, now it simply gives OOM error so it could depend on something different. 
I can print here the trace, but I don't know if it can be helpful. I tried inserting pipeline.enable_sequential_cpu_offload() in the example.py but it got blocked. 
![Schermata del 2024-12-05 00-47-32](https://github.com/user-attachments/assets/ab9be8b4-64f0-4921-933d-4142cab71159)


```

(nunchaku) inference@inference-MS-7D98:~/Scrivania/SVD_flux$ python3 example.py 
Fetching 5 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 3856.48it/s]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 13.62it/s]
You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers█████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 13.64it/s]
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 15.61it/s]
[2024-12-05 00:43:59.275] [info] Initializing QuantizedFluxModel
[2024-12-05 00:43:59.344] [info] Loading weights from /home/inference/.cache/huggingface/hub/models--mit-han-lab--svdq-int4-flux.1-schnell/snapshots/3957d6ece9852f09ccadc064f1fd25964394a490/transformer_blocks.safetensors
[2024-12-05 00:44:02.331] [info] Done.
Traceback (most recent call last):
  File "/home/inference/Scrivania/SVD_flux/example.py", line 9, in <module>
    ).to("cuda")
      ^^^^^^^^^^
  File "/home/inference/miniconda3/envs/nunchaku/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 454, in to
    module.to(device, dtype)
  File "/home/inference/miniconda3/envs/nunchaku/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3157, in to
    return super().to(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inference/miniconda3/envs/nunchaku/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1174, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/inference/miniconda3/envs/nunchaku/lib/python3.11/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/home/inference/miniconda3/envs/nunchaku/lib/python3.11/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/home/inference/miniconda3/envs/nunchaku/lib/python3.11/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  [Previous line repeated 4 more times]
  File "/home/inference/miniconda3/envs/nunchaku/lib/python3.11/site-packages/torch/nn/modules/module.py", line 805, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/home/inference/miniconda3/envs/nunchaku/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1160, in convert
    return t.to(
           ^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 32.00 MiB. GPU 0 has a total capacity of 15.69 GiB of which 22.62 MiB is free. Including non-PyTorch memory, this process has 13.82 GiB memory in use. Of the allocated memory 7.50 GiB is allocated by PyTorch, and 15.47 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
(nunchaku) inference@inference-MS-7D98:~/Scrivania/SVD_flux$ nano example.py
(nunchaku) inference@inference-MS-7D98:~/Scrivania/SVD_flux$ python3 example.py 
^C^C^C^C

```

**Comment by lmxyy** [comment]
How much GPU memory do you have?

**Comment by vgabbo** [comment]
@lmxyy I have a 4060ti with 16gb of VRAM and aside 32 gb of Ram

**Comment by lmxyy** [comment]
I see. You also need to use the quantized encoder. You can enable it with:
```python
pipeline = nunchaku_flux.from_pretrained(
    "black-forest-labs/FLUX.1-schnell",
    torch_dtype=torch.bfloat16,
    qmodel_path="mit-han-lab/svdq-int4-flux.1-schnell",  # download from Huggingface
    qencoder_path="mit-han-lab/svdquant-models/svdq-w4a16-t5.pt" if use_qencoder else None,
).to("cuda")
```
You may need to install [deepcompressor](https://github.com/mit-han-lab/deepcompressor)
```shell
git clone https://github.com/mit-han-lab/deepcompressor
cd deepcompressor
pip install poetry
poetry install
```

**Comment by lmxyy** [comment]
The issue should have been resolved in v0.0.1. We have optimized the ram usage during the model initialization. I will close this issue. Feel free to open new one if you encounter new issues.

**Comment by vgabbo** [comment]
I am really sorry I have not given a feedback. I was able to make it work thanks to your precious advice!!  @lmxyy thank you so much.
